account/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('registration_view/', views.registration_view, name="registration_view"),
    path('signIn_view/', views.signIn_view, name="signIn_view"),
    path('logout_view/', views.logout_view, name="logout_view"),
    path('sampleFuture/<str:title>', views.sampleFuture, name="sampleFuture"),
    path('home_view/', views.home_view, name="home_view"), # Beta Test URL
    
]

gameLogics/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import srBay
from . import lender

app_name = 'gameLogics'

urlpatterns = [
    path('areYouReady/', views.areYouReady, name="areYouReady"),
    path('allRanks/', views.allRanks, name="allRanks"),
    
    path('select-ship/', views.selectShip, name="selectShip"),
    path('selectShipAsCaptain/', views.selectShipAsCaptain, name="selectShipAsCaptain"),
    
    path('createGameAccount/', views.createGameAccount, name="createGameAccount"),
    path('game-starting/', views.gameStarting, name="gameStarting"),

    # Main Game
    path('mainGameDashboard/', views.mainGameDashboard, name="mainGameDashboard"),
    path('clickNextLocation/', views.clickNextLocation, name="clickNextLocation"),
    path('locations/', views.locations, name="locations"),
    
    path('RandR/', views.RandR, name="RandR"),
    path('refillCharge/', views.refillCharge, name="refillCharge"),
    path('payTax/', views.payTax, name="payTax"),
    path('payWages/', views.payWages, name="payWages"),

    path('terminal/', views.terminal, name="terminal"),
    path('hiringCrew/', views.hiringCrew, name="hiringCrew"),

    path('leisure/', views.leisure, name="leisure"),
    path('payLeisure/', views.payLeisure, name="payLeisure"),

    path('shipBay/', srBay.shipBay, name="shipBay"),
    
    path('showBuyableShips/', srBay.showBuyableShips, name="showBuyableShips"),
    path('purchaeShip/', srBay.purchaeShip, name="purchaeShip"),

    path('repair/', srBay.repair, name="repair"),
    path('maxRepair/', srBay.maxRepair, name="maxRepair"),

    path('loanMenu/', lender.loanMenu, name="loanMenu"),
    path('takingLoan/', lender.takingLoan, name="takingLoan"),
    path('repaymentNloan/', lender.repaymentNloan, name="repaymentNloan"),
    path('shipRepaymentSloan/', lender.shipRepaymentSloan, name="shipRepaymentSloan"),

    path('criticalSituation/<str:info>/<str:step>', views.criticalSituation, name="criticalSituation"),
    path('deleteGameAccount/', views.deleteGameAccount, name="deleteGameAccount"),

    # Marketplace
    path('marketplace/', views.marketplace, name="marketplace"),
    path('buyItem/', views.buyItem, name="buyItem"),
    path('sellItem/', views.sellItem, name="sellItem"),
    
    # path('giveRandomCrewmate/', views.giveRandomCrewmate, name="giveRandomCrewmate"),
    # path('dashboardShipAndCrew/', views.dashboardShipAndCrew, name="dashboardShipAndCrew"),
    
    # csv to db
    path('init/super/<str:csv_to_db>', views.super_init, name="super_init"),
    path('init_ships/<str:csv_to_db>', views.init_ships, name="init_ships"),
    path('init_crews/<str:csv_to_db>', views.init_crews, name="init_crews"),
    path('init_locations/<str:csv_to_db>', views.init_locations, name="init_locations"),
    path('init_commodities/<str:csv_to_db>', views.init_commodities, name="init_commodities"),
    # supertest
    path('supertest/', views.supertest, name="supertest"),
]

spaceGame/urls.py
from django.contrib import admin
from django.urls import path,include

from account import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('gameLogics/',include('gameLogics.urls')),

    path('', views.home_view, name="home_view"),
]

gameLogics/views.py
# from os import read
from django.shortcuts import redirect, render
from django.http import JsonResponse, request
from pathlib import Path
import csv,random,math
from .models import Ships,Crews,GameAccount,Location,Commodities,dotENV
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .custom_decorators import GameInitRequired
from .shop_logics import *
from .admin import super_init_sec
from .marketplace import validateBuy,validateSell,updateMplace
from .travel import getMyNextLocation,getDistance
from .travel import addStress,reduceShipCondition,addCIVILWAR
from .randomEvents import executeRevent
from . import DISPCARGE,CHARGE,HIGHESTNEGBALANCE,TAXRANGE
from .leaderboad import *
from .terminal import *
from .leisure import *
from .srBay import *
from .lender import denvFirstSetLoanOffer,setLoanOffer,cutInterest,isNloan,initShipLoan,isSloan,cutShipInterest

ERROR = JsonResponse({"Response" : "ERROR (X)"})


now = int(datetime.now().strftime("%d"))

# -------------------____ACCOUNT_____-----------------
# Create your views here.
def allRanks(request):
    alist = [x for x in GameAccount.objects.all().order_by('-credits')]
    allGa = []
    for x in alist:
        spl = x.ship_info['week_s']+1
        # print(x.credits,spl,(x.credits/spl))
        obj = {
            "username":x.user.username,
            "weeks":x.ship_info['week_s'],
            "credits":x.credits,
            "points":(x.credits/spl)
        }
        allGa.append(obj)
    allGa.sort(key=lambda x: x['points'], reverse=True)
    return render(request,"gameLogics/leaderboard.html",{
        "allGa":allGa
    })

@login_required
def areYouReady(request):
    user = request.user

    # C: user login check
    if not request.user.is_authenticated:
        return errorSample("Please login first / Invalid user !!!")
    
    # c: user game account check
    myGameAccount = GameAccount.objects.filter(user=user)
    if myGameAccount:
        ship = myGameAccount[0].ship_info['ship']
        if not ship:
            return redirect("gameLogics:selectShip")
        return redirect("gameLogics:mainGameDashboard")

    return render(request,"gameLogics/areYouReady.html")

@login_required
def createGameAccount(request):
    user = request.user
    if not user.is_authenticated:
        return errorSample("user not found!")
    
    myGameAccount = GameAccount.objects.filter(user=user)

    if myGameAccount:
        try:
            ship = myGameAccount[0].ship_info['ship']
            if not ship:
                return redirect("gameLogics:selectShip")
            else:
                return redirect("gameLogics:mainGameDashboard")
        except :
            return redirect("gameLogics:mainGameDashboard")
    
    create = GameAccount(user=user)
    create.save()

    return redirect("gameLogics:selectShip")

# @login_required
# def selectShipAsCaptain(request):
#     def prepare_dotENV(gameAccount):
#         user = gameAccount.user
#         location = gameAccount.location.name
#         commoditiesList=setCommoditiePrice(location)
        
#         com_json_info = {
#             "json_info" : commoditiesList,
#             "travel" : 1,
#             "terminal":getRandomCrews(request),
#         }
#         location_json_info = {
#             "json_info" : "empty"
#         }
#         denv = dotENV.objects.get_or_create(
#             user=user,
#             ga = gameAccount,
#             com_info=com_json_info,
#             location_info=location_json_info
#         )
#         dENV_setBuyableShip(request)
#         dENV_setLeisure(request)
#         denvFirstSetLoanOffer(request)

#     def asCaptain(request):
#         ga = GameAccount.objects.get(user=user)
#         ship_info = ga.ship_info
#         ship_info['ship_condition'] = 25
#         ship_info['title'] = "Captain"
#         GameAccount.objects.filter(user=request.user).update(
#             ship_info = ship_info
#         )
#         initShipLoan(request)
    
#     user = request.user
#     if not user.is_authenticated:
#         return errorSample("user not found!")
    
#     myGameAccount = GameAccount.objects.filter(user=user)

#     if myGameAccount:
#         try:
#             ship = myGameAccount[0].ship_info['ship']
#             if not ship:
#                 create = GameAccount(user=user)
#                 create.save()
#             else:
#                 return redirect("gameLogics:mainGameDashboard")
#         except :
#             return errorSample("Invalid Url! 404'As-Captain-Starting")
#     else:
#         create = GameAccount(user=user)
#         create.save()
        
#     # GA Created
#     ships = Ships.objects.all()
#     small = []
#     for ship in ships:
#         if ship.size == "Small" : small.append(ship)
    

#     small = random.sample(small, 1)[0]
#     ship_id = small.id
#     choosenShip = Ships.objects.get(id=int(ship_id))
#     randomCredit = (random.randint(1, 5))*100000

#     GameAccount.objects.filter(user=user).update(credits=randomCredit)
    
#     updatedGAccount = GameAccount.objects.get(user=user)
#     giveRandomCrewmateAndCredit(updatedGAccount,user,choosenShip)
#     gameAc2Again = GameAccount.objects.get(user=user)
#     prepare_dotENV(gameAc2Again)

#     asCaptain(request)

#     return redirect("gameLogics:gameStarting")
@login_required
def selectShipAsCaptain(request):
    def prepare_dotENV(gameAccount):
        user = gameAccount.user
        location = gameAccount.location.name
        commoditiesList=setCommoditiePrice(location)
        
        com_json_info = {
            "json_info" : commoditiesList,
            "travel" : 1,
            "terminal":getRandomCrews(request),
        }
        location_json_info = {
            "json_info" : "empty"
        }
        denv = dotENV.objects.get_or_create(
            user=user,
            ga = gameAccount,
            com_info=com_json_info,
            location_info=location_json_info
        )
        dENV_setBuyableShip(request)
        dENV_setLeisure(request)
        denvFirstSetLoanOffer(request)

    def asCaptain(request):
        ga = GameAccount.objects.get(user=user)
        ship_info = ga.ship_info
        ship_info['ship_condition'] = 25
        ship_info['title'] = "Captain"
        GameAccount.objects.filter(user=request.user).update(
            ship_info = ship_info
        )
        initShipLoan(request)
    
    user = request.user
    if request.method == "POST":
        ship_id = request.POST['ship_idX']
        choosenShip = Ships.objects.get(id=int(ship_id))
        randomCredit = (random.randint(1, 5))*100000

        GameAccount.objects.filter(user=user).update(credits=randomCredit)
        
        updatedGAccount = GameAccount.objects.get(user=user)
        giveRandomCrewmateAndCredit(updatedGAccount,user,choosenShip)
        gameAc2Again = GameAccount.objects.get(user=user)
        prepare_dotENV(gameAc2Again)
        asCaptain(request)
        # return redirect("/")
        return redirect("gameLogics:gameStarting")

@login_required
def selectShip(request):
    def prepare_dotENV(gameAccount):
        user = gameAccount.user
        location = gameAccount.location.name
        commoditiesList=setCommoditiePrice(location)
        
        com_json_info = {
            "json_info" : commoditiesList,
            "travel" : 1,
            "terminal":getRandomCrews(request),
        }
        location_json_info = {
            "json_info" : "empty"
        }
        denv = dotENV.objects.get_or_create(
            user=user,
            ga = gameAccount,
            com_info=com_json_info,
            location_info=location_json_info
        )
        dENV_setBuyableShip(request)
        dENV_setLeisure(request)
        denvFirstSetLoanOffer(request)

    user = request.user
    if not user.is_authenticated:
        return errorSample("user not found!")
    
    myGameAccount = GameAccount.objects.filter(user=user)
    if not myGameAccount:
        return errorSample("Game Account Doesent exist")
    
    try:
        ship = myGameAccount[0].ship_info['ship']
        if ship:
            return redirect("gameLogics:mainGameDashboard")
    except:
        pass

    if request.method == "POST":
        ship_id = request.POST['ship_id']
        try:
            that_id = int(ship_id)
        except:
            return errorSample("Please select a ship first!")
        choosenShip = Ships.objects.get(id=int(ship_id))
        randomCredit = (random.randint(1, 5))*100000

        GameAccount.objects.filter(user=user).update(credits=randomCredit)
        
        updatedGAccount = GameAccount.objects.get(user=user)
        giveRandomCrewmateAndCredit(updatedGAccount,user,choosenShip)
        gameAc2Again = GameAccount.objects.get(user=user)
        prepare_dotENV(gameAc2Again)
        return redirect("gameLogics:gameStarting")

    ships = Ships.objects.all()
    medium = []
    small = []
    for ship in ships:
        if ship.size == "Medium": medium.append(ship) 
        elif ship.size == "Small" : small.append(ship)
    

    small = random.sample(small, 2)
    medium = random.sample(medium, 3)
    collectedShips = medium+small

    # CAPTAIN
    ships = Ships.objects.all()
    small = []
    for ship in ships:
        if ship.size == "Small" : small.append(ship)
    

    small = random.sample(small, 1)[0]
    # EndCaptain
    return render(request,"gameLogics/selectShip.html",{
        "ships" : collectedShips,
        "small" : small
    })


@login_required
@GameInitRequired
def gameStarting(request):
    user = request.user
    gameAccount =GameAccount.objects.get(user=user)
    return render(request,"gameLogics/gameStarting.html",{
        "location": gameAccount.location,
        "gameAccount" : gameAccount
    })


# Super Helper
def checkGameAccountState(request):
    user = request.user
    if not user.is_authenticated:
        return {"res":"error","reason":"user doesn't exist!"}

gameLogics/templates/gameLogics/terminal/tbody.html
{% load humanize %}
{% for c in rc %}
    <tr class="text-center">
        <td scope="row">{{c.name}}</td>
        <td>{% if c.profession == "Fugitive" %}
            Chef
            {% else %}
            {{c.profession}}
            {% endif %}
        </td>
        <td>${{c.weeklySalary|intcomma}}</td>
        <td>${{ c.sbonus|intcomma }}</td>
        <td >
            <form action="{% url 'gameLogics:hiringCrew' %}" method="POST" class="d-flex justify-content-around align-items-stretch">
                {% csrf_token %}
                <input hidden name="crew_id" value="{{c.id}}" />
                <button type="submit" class="btn btn-outline-primary" style="width: 95%;" data-bs-toggle="modal" data-bs-target="#exampleModal-buy-{{com.id}}">
                    Hire
                </button>
            </form>
        </td>
    </tr>
{% endfor %}

gameLogics/templates/gameLogics/terminal/terminal.html
{% extends 'account/baseWithoutMove.html' %}
{% block style %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
    .nbdr{
        border-radius: 0px;
    }
    .bsw-2{
        border: 2px solid white;
    }
    .cheap{
        color:greenyellow
    }
    .mid{
        color:floralwhite
    }
    .exp{
        color:tomato;
    }
    
    .boxButton{
        padding: .8rem;
        color: white;
        background: #000000;
        border: 4px solid #FFFFFF;
        border-radius: 9px;
      }
      .boxButton:hover{
        border: 5px solid tomato;
        color: tomato;
      }
      .modelBTN{
          background-color: transparent;
          border: 4px solid white;
          color:white;
          width: 40vw;
      }
      .modelBTN:hover{
        border: 6px solid tomato;
        background-color: tomato;
      }
</style>
{% endblock %}

{% block body%}
{% load static %}

<div  style="min-height: 80vh;z-index: 999;overflow: auto;">
    <div class="d-flex justify-content-center px-4 pt-4 ">
        <div class="w-100">
            <button type="button" class="btn btn-dark w-100">
                <span class="h2">
                    Terminal 
                    <!-- <span class="h3 text-dark"></span> -->
                </span>
            </button>
        </div>
    </div>

    <div class=" d-flex justify-content-center align-items-stretch px-4">
        <!-- <div class="w-75"> -->
            <button class="btn btn-success nbdr w-50">
                Crew Mates = ({{ship_info.crews|length }}/{{ship_info.ship.crew}}) 
            </button>
        <!-- </div> -->
        <!-- <div class="w-25"> -->
            <button class="btn btn-primary nbdr w-50">
                Cash : ${{cred}}
            </button>
        <!-- </div> -->
    </div>

    <div class="py-4">
        <table class="table table-striped table-dark">
            <thead>
              <tr class="text-center">
                <th scope="col">C.Name</th>
                <th scope="col">Profession</th>
                <th scope="col">Weekly Salary</th>
                <th scope="col">Sign On</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
                {% include "gameLogics/terminal/tbody.html" %}
            </tbody>
        </table>
        <div style="text-decoration: none;" class="d-flex justify-content-end">
            <a href="/" style="text-decoration: none;" class="d-flex justify-content-end">
                <button class="btn btn-danger nbdr btn-lg">👈Back To Main Menu</button>
            </a>   
        </div>
    </div>
    
</div>

{% endblock %}

{% block script %}
<script>
</script>
{% endblock %}