account/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('registration_view/', views.registration_view, name="registration_view"),
    path('signIn_view/', views.signIn_view, name="signIn_view"),
    path('logout_view/', views.logout_view, name="logout_view"),
    path('sampleFuture/<str:title>', views.sampleFuture, name="sampleFuture"),
    path('home_view/', views.home_view, name="home_view"), # Beta Test URL
    
]

gameLogics/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import srBay
from . import lender

app_name = 'gameLogics'

urlpatterns = [
    path('areYouReady/', views.areYouReady, name="areYouReady"),
    path('allRanks/', views.allRanks, name="allRanks"),
    
    path('select-ship/', views.selectShip, name="selectShip"),
    path('selectShipAsCaptain/', views.selectShipAsCaptain, name="selectShipAsCaptain"),
    
    path('createGameAccount/', views.createGameAccount, name="createGameAccount"),
    path('game-starting/', views.gameStarting, name="gameStarting"),

    # Main Game
    path('mainGameDashboard/', views.mainGameDashboard, name="mainGameDashboard"),
    path('clickNextLocation/', views.clickNextLocation, name="clickNextLocation"),
    path('locations/', views.locations, name="locations"),
    
    path('RandR/', views.RandR, name="RandR"),
    path('refillCharge/', views.refillCharge, name="refillCharge"),
    path('payTax/', views.payTax, name="payTax"),
    path('payWages/', views.payWages, name="payWages"),

    path('terminal/', views.terminal, name="terminal"),
    path('hiringCrew/', views.hiringCrew, name="hiringCrew"),

    path('leisure/', views.leisure, name="leisure"),
    path('payLeisure/', views.payLeisure, name="payLeisure"),

    path('shipBay/', srBay.shipBay, name="shipBay"),
    
    path('showBuyableShips/', srBay.showBuyableShips, name="showBuyableShips"),
    path('purchaeShip/', srBay.purchaeShip, name="purchaeShip"),

    path('repair/', srBay.repair, name="repair"),
    path('maxRepair/', srBay.maxRepair, name="maxRepair"),

    path('loanMenu/', lender.loanMenu, name="loanMenu"),
    path('takingLoan/', lender.takingLoan, name="takingLoan"),
    path('repaymentNloan/', lender.repaymentNloan, name="repaymentNloan"),
    path('shipRepaymentSloan/', lender.shipRepaymentSloan, name="shipRepaymentSloan"),

    path('criticalSituation/<str:info>/<str:step>', views.criticalSituation, name="criticalSituation"),
    path('deleteGameAccount/', views.deleteGameAccount, name="deleteGameAccount"),

    # Marketplace
    path('marketplace/', views.marketplace, name="marketplace"),
    path('buyItem/', views.buyItem, name="buyItem"),
    path('sellItem/', views.sellItem, name="sellItem"),
    
    # path('giveRandomCrewmate/', views.giveRandomCrewmate, name="giveRandomCrewmate"),
    # path('dashboardShipAndCrew/', views.dashboardShipAndCrew, name="dashboardShipAndCrew"),
    
    # csv to db
    path('init/super/<str:csv_to_db>', views.super_init, name="super_init"),
    path('init_ships/<str:csv_to_db>', views.init_ships, name="init_ships"),
    path('init_crews/<str:csv_to_db>', views.init_crews, name="init_crews"),
    path('init_locations/<str:csv_to_db>', views.init_locations, name="init_locations"),
    path('init_commodities/<str:csv_to_db>', views.init_commodities, name="init_commodities"),
    # supertest
    path('supertest/', views.supertest, name="supertest"),
]

spaceGame/urls.py
from django.contrib import admin
from django.urls import path,include

from account import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('gameLogics/',include('gameLogics.urls')),

    path('', views.home_view, name="home_view"),
]

gameLogics/views.py
# from os import read
from django.shortcuts import redirect, render
from django.http import JsonResponse, request
from pathlib import Path
import csv,random,math
from .models import Ships,Crews,GameAccount,Location,Commodities,dotENV
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .custom_decorators import GameInitRequired
from .shop_logics import *
from .admin import super_init_sec
from .marketplace import validateBuy,validateSell,updateMplace
from .travel import getMyNextLocation,getDistance
from .travel import addStress,reduceShipCondition,addCIVILWAR
from .randomEvents import executeRevent
from . import DISPCARGE,CHARGE,HIGHESTNEGBALANCE,TAXRANGE
from .leaderboad import *
from .terminal import *
from .leisure import *
from .srBay import *
from .lender import denvFirstSetLoanOffer,setLoanOffer,cutInterest,isNloan,initShipLoan,isSloan,cutShipInterest

ERROR = JsonResponse({"Response" : "ERROR (X)"})


now = int(datetime.now().strftime("%d"))

# -------------------____ACCOUNT_____-----------------
# Create your views here.
def allRanks(request):
    alist = [x for x in GameAccount.objects.all().order_by('-credits')]
    allGa = []
    for x in alist:
        spl = x.ship_info['week_s']+1
        # print(x.credits,spl,(x.credits/spl))
        obj = {
            "username":x.user.username,
            "weeks":x.ship_info['week_s'],
            "credits":x.credits,
            "points":(x.credits/spl)
        }
        allGa.append(obj)
    allGa.sort(key=lambda x: x['points'], reverse=True)
    return render(request,"gameLogics/leaderboard.html",{
        "allGa":allGa
    })

@login_required
def areYouReady(request):
    user = request.user

    # C: user login check
    if not request.user.is_authenticated:
        return errorSample("Please login first / Invalid user !!!")
    
    # c: user game account check
    myGameAccount = GameAccount.objects.filter(user=user)
    if myGameAccount:
        ship = myGameAccount[0].ship_info['ship']
        if not ship:
            return redirect("gameLogics:selectShip")
        return redirect("gameLogics:mainGameDashboard")

    return render(request,"gameLogics/areYouReady.html")

@login_required
def createGameAccount(request):
    user = request.user
    if not user.is_authenticated:
        return errorSample("user not found!")
    
    myGameAccount = GameAccount.objects.filter(user=user)

    if myGameAccount:
        try:
            ship = myGameAccount[0].ship_info['ship']
            if not ship:
                return redirect("gameLogics:selectShip")
            else:
                return redirect("gameLogics:mainGameDashboard")
        except :
            return redirect("gameLogics:mainGameDashboard")
    
    create = GameAccount(user=user)
    create.save()

    return redirect("gameLogics:selectShip")

# @login_required
# def selectShipAsCaptain(request):
#     def prepare_dotENV(gameAccount):
#         user = gameAccount.user
#         location = gameAccount.location.name
#         commoditiesList=setCommoditiePrice(location)
        
#         com_json_info = {
#             "json_info" : commoditiesList,
#             "travel" : 1,
#             "terminal":getRandomCrews(request),
#         }
#         location_json_info = {
#             "json_info" : "empty"
#         }
#         denv = dotENV.objects.get_or_create(
#             user=user,
#             ga = gameAccount,
#             com_info=com_json_info,
#             location_info=location_json_info
#         )
#         dENV_setBuyableShip(request)
#         dENV_setLeisure(request)
#         denvFirstSetLoanOffer(request)

#     def asCaptain(request):
#         ga = GameAccount.objects.get(user=user)
#         ship_info = ga.ship_info
#         ship_info['ship_condition'] = 25
#         ship_info['title'] = "Captain"
#         GameAccount.objects.filter(user=request.user).update(
#             ship_info = ship_info
#         )
#         initShipLoan(request)
    
#     user = request.user
#     if not user.is_authenticated:
#         return errorSample("user not found!")
    
#     myGameAccount = GameAccount.objects.filter(user=user)

#     if myGameAccount:
#         try:
#             ship = myGameAccount[0].ship_info['ship']
#             if not ship:
#                 create = GameAccount(user=user)
#                 create.save()
#             else:
#                 return redirect("gameLogics:mainGameDashboard")
#         except :
#             return errorSample("Invalid Url! 404'As-Captain-Starting")
#     else:
#         create = GameAccount(user=user)
#         create.save()
        
#     # GA Created
#     ships = Ships.objects.all()
#     small = []
#     for ship in ships:
#         if ship.size == "Small" : small.append(ship)
    

#     small = random.sample(small, 1)[0]
#     ship_id = small.id
#     choosenShip = Ships.objects.get(id=int(ship_id))
#     randomCredit = (random.randint(1, 5))*100000

#     GameAccount.objects.filter(user=user).update(credits=randomCredit)
    
#     updatedGAccount = GameAccount.objects.get(user=user)
#     giveRandomCrewmateAndCredit(updatedGAccount,user,choosenShip)
#     gameAc2Again = GameAccount.objects.get(user=user)
#     prepare_dotENV(gameAc2Again)

#     asCaptain(request)

#     return redirect("gameLogics:gameStarting")
@login_required
def selectShipAsCaptain(request):
    def prepare_dotENV(gameAccount):
        user = gameAccount.user
        location = gameAccount.location.name
        commoditiesList=setCommoditiePrice(location)
        
        com_json_info = {
            "json_info" : commoditiesList,
            "travel" : 1,
            "terminal":getRandomCrews(request),
        }
        location_json_info = {
            "json_info" : "empty"
        }
        denv = dotENV.objects.get_or_create(
            user=user,
            ga = gameAccount,
            com_info=com_json_info,
            location_info=location_json_info
        )
        dENV_setBuyableShip(request)
        dENV_setLeisure(request)
        denvFirstSetLoanOffer(request)

    def asCaptain(request):
        ga = GameAccount.objects.get(user=user)
        ship_info = ga.ship_info
        ship_info['ship_condition'] = 25
        ship_info['title'] = "Captain"
        GameAccount.objects.filter(user=request.user).update(
            ship_info = ship_info
        )
        initShipLoan(request)
    
    user = request.user
    if request.method == "POST":
        ship_id = request.POST['ship_idX']
        choosenShip = Ships.objects.get(id=int(ship_id))
        randomCredit = (random.randint(1, 5))*100000

        GameAccount.objects.filter(user=user).update(credits=randomCredit)
        
        updatedGAccount = GameAccount.objects.get(user=user)
        giveRandomCrewmateAndCredit(updatedGAccount,user,choosenShip)
        gameAc2Again = GameAccount.objects.get(user=user)
        prepare_dotENV(gameAc2Again)
        asCaptain(request)
        # return redirect("/")
        return redirect("gameLogics:gameStarting")

@login_required
def selectShip(request):
    def prepare_dotENV(gameAccount):
        user = gameAccount.user
        location = gameAccount.location.name
        commoditiesList=setCommoditiePrice(location)
        
        com_json_info = {
            "json_info" : commoditiesList,
            "travel" : 1,
            "terminal":getRandomCrews(request),
        }
        location_json_info = {
            "json_info" : "empty"
        }
        denv = dotENV.objects.get_or_create(
            user=user,
            ga = gameAccount,
            com_info=com_json_info,
            location_info=location_json_info
        )
        dENV_setBuyableShip(request)
        dENV_setLeisure(request)
        denvFirstSetLoanOffer(request)

    user = request.user
    if not user.is_authenticated:
        return errorSample("user not found!")
    
    myGameAccount = GameAccount.objects.filter(user=user)
    if not myGameAccount:
        return errorSample("Game Account Doesent exist")
    
    try:
        ship = myGameAccount[0].ship_info['ship']
        if ship:
            return redirect("gameLogics:mainGameDashboard")
    except:
        pass

    if request.method == "POST":
        ship_id = request.POST['ship_id']
        try:
            that_id = int(ship_id)
        except:
            return errorSample("Please select a ship first!")
        choosenShip = Ships.objects.get(id=int(ship_id))
        randomCredit = (random.randint(1, 5))*100000

        GameAccount.objects.filter(user=user).update(credits=randomCredit)
        
        updatedGAccount = GameAccount.objects.get(user=user)
        giveRandomCrewmateAndCredit(updatedGAccount,user,choosenShip)
        gameAc2Again = GameAccount.objects.get(user=user)
        prepare_dotENV(gameAc2Again)
        return redirect("gameLogics:gameStarting")

    ships = Ships.objects.all()
    medium = []
    small = []
    for ship in ships:
        if ship.size == "Medium": medium.append(ship) 
        elif ship.size == "Small" : small.append(ship)
    

    small = random.sample(small, 2)
    medium = random.sample(medium, 3)
    collectedShips = medium+small

    # CAPTAIN
    ships = Ships.objects.all()
    small = []
    for ship in ships:
        if ship.size == "Small" : small.append(ship)
    

    small = random.sample(small, 1)[0]
    # EndCaptain
    return render(request,"gameLogics/selectShip.html",{
        "ships" : collectedShips,
        "small" : small
    })


@login_required
@GameInitRequired
def gameStarting(request):
    user = request.user
    gameAccount =GameAccount.objects.get(user=user)
    return render(request,"gameLogics/gameStarting.html",{
        "location": gameAccount.location,
        "gameAccount" : gameAccount
    })


# Super Helper
def checkGameAccountState(request):
    user = request.user
    if not user.is_authenticated:
        return {"res":"error","reason":"user doesn't exist!"}

gameLogics/templates/gameLogics/areYouReady.html
{% extends 'account/base.html' %}
{% block style %}
<style>
    .boxButton{
        padding: .8rem;
        color: white;
        background: #000000;
        border: 4px solid #FFFFFF;
        border-radius: 9px;
      }
      .boxButton:hover{
        border: 5px solid tomato;
        color: tomato;
      }
</style>
{% endblock %}

{% block body%}
{% load static %}

<div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
    <div>
        <h1 class="display-2 text-center">Are You Ready To Start Your Journey?</h1>
        <div class="d-flex justify-content-around align-items-center" style="margin-top: 4vh;">
            <a style="text-decoration: none;" href="{% url 'gameLogics:createGameAccount' %}" class="boxButton h1">Yes</a>
            <a style="text-decoration: none;" href="{% url 'account:logout_view' %}" class="boxButton h1">No</a>
        </div>
    </div>
</div>

{% endblock %}

gameLogics/templates/gameLogics/dashboard.html
{% extends 'account/baseWithoutMove.html' %}
{% block style %}
<style>
    .nbdr{
        border-radius: 0px;
    }
</style>
{% endblock %}

{% block body%}
{% load static %}

<!-- <div class="d-flex justify-content-around " style="min-height: 80vh;z-index: 999;overflow: auto;"> -->
<div class="" style="min-height: 80vh;z-index: 999;overflow: auto;">
    <div class="d-flex justify-content-between p-4">
        <div>
            <div class="d-flex justify-content-center align-items-center">
                <div class="w-100">
                    <div class="d-flex justify-content-center">
                        <img style="z-index: -99;width: 30vw; border: 5px whitesmoke solid;" src="/static/gameLogics/images/{{location.name}}.png"/>
                    </div>
                    <div class="w-100 d-flex justify-content-end">
                        <div>
                            <h4 class="bg-dark" style="padding: 12px; margin-top: 8px;">Location || {{location.name}}</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div style="border: 5px solid orange;width: 100%;">
                <div style="width: 100%;">
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-warning nbdr w-25">
                            Name
                        </button>
                        <button class="btn btn-warning nbdr w-25">
                            Health
                        </button>
                        <button class="btn btn-warning nbdr w-25">
                            Hunger
                        </button>
                        <button class="btn btn-warning nbdr w-25">
                            Resolve
                        </button>
                        <button class="btn btn-warning nbdr w-25">
                            Stress
                        </button>
                    </div>
                    {% for crew in crews %}
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-dark nbdr w-25">
                            {{crew.name}}
                        </button>
                        <button class="btn btn-dark nbdr w-25">
                            {{crew.health}}
                        </button>
                        <button class="btn btn-dark nbdr w-25">
                            {{crew.hunger}}
                        </button>
                        <button class="btn btn-dark nbdr w-25">
                            {{crew.resolve}}
                        </button>
                        <button class="btn btn-dark nbdr w-25">
                            {{crew.stress}}
                        </button>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Ship -->
        <div class="d-flex justify-content-center mx-4" style="background-color: transparent;width: 100%; border: 5px solid white;">
            <div class="d-flex justify-content-center align-items-center">
                <div>
                    <div class="d-flex justify-content-center">
                        <img width="60%" src="{% static 'account/images/running.gif' %}" />
                    </div>
                    <h1 class="text-center">Coming Soon!!!
                        <a style="text-decoration: underline;" class="text-danger" href="{% url 'account:logout_view' %}" >Logout</a>
                    </h1>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
</script>
{% endblock %}

gameLogics/templates/gameLogics/gameStarting.html
{% extends 'account/baseWithoutMove.html' %}
{% block style %}
<style>
</style>
{% endblock %}

{% block body%}
{% load static %}

<div class="d-flex justify-content-around align-items-center" style="min-height: 80vh;z-index: 999;overflow: auto;">
    <img onload="typeWriter()" style="z-index: -99; width:30%;border: 5px white solid;" src="/static/gameLogics/images/{{location.name}}.png"/>
    <div>
        <div>
            <span class="display-1 text-center">Welcome to <span class="display-1 text-center text-warning" id="type"></span></span>
        </div>
        <div>
            <span>
                <span class="h2">You have <span class="text-primary">{{gameAccount.credits}}$</span> Credits.<span class="text-danger">Your journey has begun!</span></span>
            </span>
        </div>

        <a href="/" class="d-flex justify-content-center mt-4" style="text-decoration: none;">
            <button  class="btn btn-warning" style="font-size: xx-large;">Prepare for your next destination </button>
        </a>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
    var i = 0;
    var txt = "{{location.name}}";
    var speed = 250;
    function typeWriter() {
        if (i < txt.length) {
            document.getElementById("type").innerHTML += txt.charAt(i);
            i++;
            setTimeout(typeWriter, speed);
        }
    }
</script>
{% endblock %}

gameLogics/templates/gameLogics/leaderboard.html
{% extends 'account/baseWithoutMove.html' %}
{% block style %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
    .nbdr{
        border-radius: 0px;
    }
    .bsw-2{
        border: 2px solid white;
    }
    .cheap{
        color:greenyellow
    }
    .mid{
        color:floralwhite
    }
    .exp{
        color:tomato;
    }
    
    .boxButton{
        padding: .8rem;
        color: white;
        background: #000000;
        border: 4px solid #FFFFFF;
        border-radius: 9px;
      }
      .boxButton:hover{
        border: 5px solid tomato;
        color: tomato;
      }
      .modelBTN{
          background-color: transparent;
          border: 4px solid white;
          color:white;
          width: 40vw;
      }
      .modelBTN:hover{
        border: 6px solid tomato;
        background-color: tomato;
      }
</style>
{% endblock %}

{% block body%}
{% load static %}

<div  style="min-height: 80vh;z-index: 999;overflow: auto;">
    <div class="d-flex justify-content-center px-4 pt-4 ">
        <div class="d-flex w-100">
            <button type="button" class="btn nbdr btn-dark w-100">
                <span class="h2">
                    Rank 
                </span>
            </button>
            <!-- <button type="button" class="btn nbdr btn-warning  w-25" data-bs-toggle="modal" data-bs-target="#exampleModal">
                <span class="h2 disabled">
                    Crews 
                </span>
            </button> -->
        </div>
    </div>

    <div class="py-4">
        <table class="table table-striped table-dark">
            <thead>
              <tr class="text-center">
                <th scope="col">No</th>
                <th scope="col">Username</th>
                <th scope="col">Weeks</th>
                <th scope="col">Credits</th>
              </tr>
            </thead>
            <tbody>
                {% load humanize %}
                    {% for c in allGa %}
                        <tr class="text-center">
                            <td scope="row">{{ forloop.counter }}</td>
                            <td scope="row">{{c.username}} </td>
                            <td>{{c.weeks}}</td>
                            <td>${{c.credits|intcomma}}</td>
                            </td>
                        </tr>
                    {% endfor %}
            </tbody>
        </table>
        <div style="text-decoration: none;" class="d-flex justify-content-end">
            <a href="/" style="text-decoration: none;" class="d-flex justify-content-end">
                <button class="btn btn-danger nbdr btn-lg">👈Back To Main Menu</button>
            </a>   
        </div>
    </div>
    
</div>

{% endblock %}

{% block script %}
<script>
</script>
{% endblock %}

gameLogics/templates/gameLogics/mainGameDashboard.html
{% extends 'account/base.html' %}
{% block style %}
<style>
</style>
{% endblock %}
{% block body%}
{% load static %}

<div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
    <div>
        
        <div class="d-flex justify-content-between" >
            <h2 class="text-warning">Crew Members</h2>
            <button class="btn btn-danger"><h3>Ship || {{ship}}</h3></button>
        </div>
        <table class="table h3">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Profession</th>
                <th scope="col">Salary</th>
              </tr>
            </thead>
            <tbody>
              {% for crew in crewMembers %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{crew.name}}</td>
                <td>{{crew.profession}}</td>
                <td>{{crew.weeklySalary}}$</td>
              </tr>
              {% endfor %}
            </tbody>
        </table>

        <div>
            <div class="d-flex justify-content-center">
                <img width="20%" src="{% static 'account/images/running.gif' %}" />
            </div>
            <h1 class="text-center">Coming Soon!!!
                <a style="text-decoration: underline;" class="text-danger" href="{% url 'account:logout_view' %}" >Logout</a>
            </h1>
        </div>
    </div>
</div>

{% endblock %}

gameLogics/templates/gameLogics/selectShip.html
{% extends 'account/base.html' %}
{% block style %}
<style>
    .boxButton{
        padding: .8rem;
        color: white;
        background: #000000;
        border: 4px solid #FFFFFF;
        border-radius: 9px;
      }
      .boxButton:hover{
        border: 5px solid tomato;
        color: tomato;
      }
      .modelBTN{
          background-color: transparent;
          border: 4px solid white;
          color:white;
          width: 65vw;
      }
      .modelBTN:hover{
        border: 6px solid tomato;
        background-color: tomato;
      }
</style>
{% endblock %}

{% block body%}
{% load static %}
{% load humanize %}
<div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;z-index: 999;overflow: auto;">
    <div>
        <h1 class="display-2 text-center text-warning">Hi,{{ user.username }}</h1>
        <div class="d-flex justify-content-center p-3">
            <span class="w-75 text-center h3">
                The following ships are looking for a new Purser to run their ship operations.
                You will be <span class="text-danger"> responsible </span> for <span class="text-danger"> buying </span> and <span class="text-danger"> selling </span> commodities, <span class="text-danger"> paying crew wages and taxes </span>, ship repairs and <span class="text-danger"> maintenance </span>. Of course, the job comes with perks.
            </span>
        </div>
        <h1 class="text-center text-primary">Choose the ship you want to join:</h1>
        <div class="d-flex justify-content-center" style="margin-bottom: 4vh;">
            <div>
                {% for ship in ships %}
                <div>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn modelBTN m-2 btngrab" id="#ship{{ship.id}}" onclick="active(this)" value="{{ship.id}}">
                        <h1 class="h1">The {{ship.name}} - {{ship.size}} size {{ship.type}} - Crew: {{ship.crew}}</h1>
                    </button>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="d-flex justify-content-center p-3">
            <span class="w-75 text-center text-warning fs-2">
                OR, Finance This Ship And Be The Captain .This Ship Cost ${{small.value|intcomma}} & <br> Monthly Interest 1%
            </span>
        </div>
        <form method="POST" action="{% url 'gameLogics:selectShipAsCaptain' %}" class="d-flex justify-content-center">
            {% csrf_token %}
            <input name="ship_idX" value="{{small.id}}" hidden />
            <button type="submit" class="btn btn-success modelBTN m-2 btngrab">
                <h1 class="h1">The {{small.name}} - {{small.size}} size {{small.type}} - Crew: {{small.crew}}</h1>
            </button>
        </form>

        <form action="" class="mt-4" method="post">
            <input id="val" name="ship_id" hidden value="" />
            <div class="d-flex justify-content-center " style="margin-bottom: 8vh;">
                {% csrf_token %}
                <button type="submit" class="btn btn-warning w-25">
                    <h1>Next</h1>
                </button>
            </div>
        </form>

        
    </div>
</div>

{% endblock %}

{% block script %}
<script>
    const active = (ele) =>{
        listOfclass = document.querySelectorAll(".btngrab")
        console.log(listOfclass)
        for (i = 0; i < listOfclass.length; i++) {
            listOfclass[i].style.backgroundColor = "transparent";
        }
        selected = ele.style.background = "tomato";
        document.getElementById("val").value = ele.value
        console.log(ele.value);
    }
</script>
{% endblock %}